# Generated by Django 3.2.14 on 2022-07-09 11:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payee', related_query_name='payee', to='accounts.bankaccounts')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payer', related_query_name='payer', to='accounts.bankaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower', related_query_name='borrower', to='accounts.bankaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountTransactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user_type', models.CharField(choices=[('LOAN', 'LOAN'), ('PAYMENT', 'PAYMENT')], default='INDIVIDUAL', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_from', related_query_name='account_from', to='accounts.bankaccounts')),
                ('account_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_to', related_query_name='account_to', to='accounts.bankaccounts')),
            ],
        ),
    ]
